<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-060IDNG" failures="0" tests="3" name="testcase.Demo3_SFWithElementMethod.AccountTest" time="53.211" errors="1" timestamp="2020-05-14T00:25:55 IST" skipped="2">
  <testcase classname="testcase.Demo3_SFWithElementMethod.AccountTest" name="createAccount" time="53.211">
    <error message="Element not found :-Account Name" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Element not found :-Account Name
at com.solveurits.automation.SalesforceAT.sfFormFieldMethod(SalesforceAT.java:475)
at com.solveurits.automation.SalesforceAT.sfFormField(SalesforceAT.java:373)
at features.Accounts.fillAccountDetails(Accounts.java:34)
at features.Accounts.createAccount(Accounts.java:248)
at testcase.Demo3_SFWithElementMethod.AccountTest.createAccount(AccountTest.java:90)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
    </error>
  </testcase> <!-- createAccount -->
  <testcase classname="testcase.Demo3_SFWithElementMethod.AccountTest" name="addActivity" time="0.000">
    <skipped/>
  </testcase> <!-- addActivity -->
  <testcase classname="testcase.Demo3_SFWithElementMethod.AccountTest" name="addChatter" time="0.000">
    <skipped/>
  </testcase> <!-- addChatter -->
</testsuite> <!-- testcase.Demo3_SFWithElementMethod.AccountTest -->
